### ISSUE TITLE
Add e2e tests that use fully timestamp massaged rooms

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix-public-archive#169]
Currently, we can only timestamp massage the events sent in the room after creation using `/send?ts=123` and `/state?ts=123` but this leaves the primordial room creation and federated join/membership events still at current time which throws things off sometimes.

I've created a few MSC's to track getting us to fully timestamp massaged rooms that appear to be created back in time:

 - [MSC3997](https://github.com/matrix-org/matrix-spec-proposals/pull/3997): Add timestamp massaging to `/createRoom?ts=123`
 - [MSC3998](https://github.com/matrix-org/matrix-spec-proposals/pull/3998): Add timestamp massaging to `/join?ts=123` and `/knock?ts=123`

But it's also good to test the scenario with our current flawed setup. This is basically what the Gitter historical rooms look like where the room creation happened at time A and the events look like they were sent before time A.

### Todo

 - [ ] Create/wait for unstable versions in Synapse to use
 - [ ] Add test variations for fully timestamp massaged rooms
 - [ ] Keep test variation around for partial timestamp massaged rooms as we have now (useful to make sure Gitter-like historical rooms work)
